Docs/cli
obytes/app-icon-badge pull request #28
Opened 2023-09-01 12:04 UTC by 0x10Ayoub

- explain how cli features works in readme file 
 - update help message for the add-badge command

2023-09-01 14:44 UTC, yjose requested changes

2023-09-01 14:44 UTC, yjose commented on README.md
> +## as a CLi
I think you should add npx here `npx app-icon-badge ......`

2023-09-04 10:15 UTC, SihamBen submitted a review, later dismissed
🥇

2023-09-04 20:43 UTC, yjose approved these changes

2023-09-04 21:12 UTC, merged