fix(plugin): refactor to use withDangerousMod
obytes/app-icon-badge pull request #34
Opened 2024-09-03 07:47 UTC by janwiebe-jump

Rewrote the plugin to use withDangerousMod so the addBadge call can be awaited
Fixes #31

2024-09-03 15:09 UTC, yjose requested changes

2024-09-03 15:16 UTC, janwiebe-jump commented on app.plugin.ts
>    const iconPath = config?.icon;
Thanks for reviewing, oversighted the unreachable code

2024-10-21 22:27 UTC, 0x1337ak approved these changes
LGTM
![Screenshot 2024-10-21 at 23 26 58](https://github.com/user-attachments/assets/b8888345-15b4-42a5-a018-ed34d5e25a2d)

2024-10-22 10:47 UTC, yjose approved these changes

2024-10-22 10:49 UTC, yjose commented
Thank you @0x1337ak  for taking time to test and review the updates 🙏
Thank you, @janwiebe-jump, for your contribution. I will merge the PR and publish a new alpha version of the plugin so we can conduct more tests on a real application.

2024-10-22 10:49 UTC, merged